import { createApp } from 'vue';
import App from './App.vue';
import { installCanvasPersistence } from './canvas-persistence';
import { installImageLightbox } from './image-lightbox';
import { installInspectorOriginTracking } from './inspector-origin';
import './themes.css';
import './styles.css';
import './world-surfaces.css';
import './delete-markers.css';
import './mobile-command-bar.css';
import './mobile-prompt-safe.css';
import './delete-transition.css';
import './seed-dot-motion.css';
import './bubble-shape.css';
import './closed-open-bubbles.css';
import './artifact-open-guard.css';
import './inspector-genie.css';
import './fork-split.css';
import './ai-artifacts.css';
import './nested-bubbles.css';
import './model-picker.css';
import './ghost-suggestions.css';
import './connections.css';
import './canvas-persistence.css';
import './image-lightbox.css';
import './artifact-open-guard';

installInspectorOriginTracking();
installImageLightbox();
const app = createApp(App);
const root = app.mount('#app');
installCanvasPersistence(root);
